import Navigation from "@/components/navigation"
import Footer from "@/components/footer"
import { academyAccreditation } from "@/lib/academy-data"

export default function AboutPage() {
  return <div className="min-h-screen bg-background"><Navigation /><main>
    <section className="bg-forest px-6 py-20 text-white md:py-28"><div className="container mx-auto lg:px-10"><p className="eyebrow text-gold">À propos de Global Academy</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-bold leading-tight sm:text-5xl md:text-6xl">Préparer la jeunesse aux métiers de la <span className="text-gold">nouvelle économie.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/75 md:text-lg">Une école vocationnelle engagée pour l&apos;employabilité, l&apos;autonomie et l&apos;ouverture internationale, dans un monde transformé par l&apos;intelligence artificielle.</p></div></section>
    <section className="container mx-auto grid gap-10 px-6 py-16 md:grid-cols-2 md:py-20 lg:px-10"><div><p className="eyebrow">Notre mission</p><h2 className="mt-3 font-serif text-3xl font-bold text-forest sm:text-4xl">Former des professionnels prêts pour le monde réel.</h2></div><div className="space-y-5 leading-8 text-muted-foreground"><p>Global Academy est une école vocationnelle avec accord du MINFOP. Nous préparons les jeunes aux nouvelles exigences du marché national et international, notamment avec la montée de l&apos;IA et du travail à distance.</p><p>Nos formations associent compétences pratiques, culture numérique, communication professionnelle et accompagnement humain pour transformer les talents en opportunités concrètes.</p><p>Grâce à notre partenariat avec <a className="font-bold text-forest underline" href="https://freelanceconnect.cm">FreelanceConnect</a>, les apprenants peuvent découvrir les méthodes de freelances chevronnés et de professionnels du remote.</p></div></section>
    <section className="bg-cream px-6 py-16"><div className="container mx-auto grid gap-8 md:grid-cols-[1fr_auto] md:items-center lg:px-10"><div><p className="eyebrow">Reconnaissance institutionnelle</p><h2 className="mt-3 font-serif text-3xl font-bold text-forest">Une vocation professionnelle reconnue.</h2><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Global Academy construit des parcours professionnalisants avec un cadre clair et une exigence adaptée aux réalités de l&apos;emploi.</p><p className="mt-5 font-bold text-forest">{academyAccreditation}</p></div><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Capture%20d%E2%80%99%C3%A9cran%202026-09-17%20095427-Olngit0GQ97m6OcE6gzm9Z0bVSKjN7.png" alt="Extrait de l'accord du MINFOP de Global Academy" width="620" height="110" className="w-full max-w-xl rounded border border-border bg-white object-contain" /></div></section>
  </main><Footer /></div>
}
