"use client"

import { useState } from "react"
import Link from "next/link"
import { ArrowRight, CheckCircle2, LockKeyhole, PlayCircle } from "lucide-react"
import Navigation from "@/components/navigation"
import Footer from "@/components/footer"
import { aiFluencyLessons, dummyLearner } from "@/lib/academy-data"

export default function AiFluencyPage() {
  const [active, setActive] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const lesson = aiFluencyLessons[active]
  const question = lesson.quiz[0]
  const answered = selected !== null

  return <div className="min-h-screen bg-background"><Navigation /><main>
    <section className="bg-forest px-6 py-16 text-white md:py-24"><div className="container mx-auto lg:px-10"><p className="eyebrow text-gold">Cours à la demande · Démo</p><h1 className="mt-4 max-w-3xl font-serif text-4xl font-bold text-balance md:text-6xl">AI Fluency : mieux comprendre, mieux utiliser l&apos;IA.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">Un premier parcours pratique pour développer une culture de l&apos;IA, vérifier ses résultats et agir avec responsabilité.</p></div></section>
    <section className="container mx-auto grid gap-8 px-6 py-12 lg:grid-cols-[.75fr_1.25fr] lg:px-10 lg:py-16">
      <aside className="h-fit rounded-xl border border-border bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm font-bold uppercase tracking-widest text-gold-dark">Votre parcours</p><span className="text-sm text-muted-foreground">{active + 1}/{aiFluencyLessons.length}</span></div><div className="mt-4 grid gap-2">{aiFluencyLessons.map((item, index) => <button key={item.id} onClick={() => { setActive(index); setSelected(null) }} className={`flex items-start gap-3 rounded-lg p-3 text-left transition ${index === active ? "bg-forest text-white" : "hover:bg-secondary"}`}><span className={`mt-0.5 rounded-full p-1 ${index === active ? "bg-gold text-forest" : "bg-secondary text-forest"}`}><PlayCircle className="h-4 w-4" /></span><span><span className="block text-sm font-bold">{item.title}</span><span className={`mt-1 block text-xs ${index === active ? "text-white/65" : "text-muted-foreground"}`}>{index === 0 ? "Disponible" : "À venir"}</span></span></button>)}</div><div className="mt-5 border-t border-border pt-5 text-sm text-muted-foreground"><p className="flex gap-2"><LockKeyhole className="h-4 w-4 shrink-0 text-gold-dark" /> Accès démonstration uniquement. L&apos;inscription sera activée après validation de votre dossier.</p></div></aside>
      <div><div className="overflow-hidden rounded-xl bg-black shadow-lg"><div className="aspect-video"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${lesson.videoId}?rel=0&modestbranding=1`} title={lesson.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div></div><div className="mt-8"><p className="eyebrow">Leçon {active + 1}</p><h2 className="mt-2 font-serif text-3xl font-bold text-forest">{lesson.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{lesson.description}</p><div className="mt-8 rounded-xl border border-border bg-white p-6"><p className="text-sm font-bold uppercase tracking-widest text-gold-dark">Quiz rapide</p><h3 className="mt-3 text-lg font-bold text-forest">{question.question}</h3><div className="mt-4 grid gap-2">{question.options.map((option, index) => <button key={option} onClick={() => setSelected(index)} className={`rounded-lg border p-3 text-left text-sm transition ${selected === index ? index === question.answer ? "border-green-600 bg-green-50 text-green-800" : "border-destructive bg-red-50 text-red-800" : "border-border hover:border-forest"}`}>{option}</button>)}</div>{answered && <p className="mt-4 flex items-center gap-2 text-sm font-semibold text-forest"><CheckCircle2 className="h-4 w-4 text-gold-dark" /> {selected === question.answer ? "Bonne réponse. Continuez votre parcours." : "Pas encore. Relisez la question et essayez de nouveau."}</p>}</div><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-between">{active < aiFluencyLessons.length - 1 ? <button onClick={() => { setActive(active + 1); setSelected(null) }} className="inline-flex items-center justify-center gap-2 rounded-md bg-forest px-5 py-3 font-bold text-white hover:bg-forest-light">Leçon suivante <ArrowRight className="h-4 w-4" /></button> : <Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-md bg-gold px-5 py-3 font-bold text-forest">Demander l&apos;accès <ArrowRight className="h-4 w-4" /></Link>}<p className="self-center text-xs text-muted-foreground">Démo : {dummyLearner.email} · {dummyLearner.password}</p></div></div></div>
    </section></main><Footer /></div>
}
