"use client"

import { useMemo, useState } from "react"
import Navigation from "@/components/navigation"
import Footer from "@/components/footer"
import { CheckCircle2, Filter, ShieldCheck } from "lucide-react"
import { academyAccreditation, academyPrograms, freeShortCourses } from "@/lib/academy-data"

const filters = [
  { id: "all", label: "Toutes les formations" },
  { id: "short-course", label: "Short courses" },
  { id: "lab", label: "Labs à reprendre" },
  { id: "free", label: "Gratuites" },
] as const

export default function ProgramsPage() {
  const [activeFilter, setActiveFilter] = useState<(typeof filters)[number]["id"]>("all")
  const showProfessional = activeFilter === "all"
  const showFree = activeFilter === "all" || activeFilter === "short-course" || activeFilter === "lab" || activeFilter === "free"
  const visibleFreeCourses = useMemo(() => freeShortCourses.filter((course) => {
    if (activeFilter === "free") return true
    if (activeFilter === "lab") return (course.tags as readonly string[]).includes("lab")
    if (activeFilter === "short-course") return (course.tags as readonly string[]).includes("short-course")
    return true
  }), [activeFilter])

  return <div className="min-h-screen bg-background"><Navigation /><main>
    <section className="bg-forest px-6 py-20 text-white md:py-28"><div className="container mx-auto lg:px-10"><p className="eyebrow text-gold">Nos formations professionnelles</p><h1 className="mt-4 max-w-3xl font-serif text-5xl font-bold md:text-6xl">Des compétences pour <span className="text-gold">l’emploi.</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/75">Des diplômes professionnels, des short courses et des labs pratiques pour apprendre à son rythme, progresser dans l’IA et répondre aux besoins du travail local et international.</p><div className="mt-7 inline-flex max-w-2xl items-start gap-3 rounded-lg border border-gold/35 bg-white/5 px-4 py-3 text-sm text-white/85"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-gold" /><span>Global Academy est un centre de formation professionnelle agréé par le MINEFOP · {academyAccreditation}</span></div></div></section>
    <section className="container mx-auto px-6 py-12 lg:px-10 lg:py-16"><div className="flex flex-col gap-5 border-b border-border pb-7 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-gold-dark">Catalogue</p><h2 className="mt-2 font-serif text-3xl font-bold text-forest">Choisissez votre format d’apprentissage</h2><p className="mt-2 max-w-2xl text-muted-foreground">Les formations gratuites sont certifiantes. Les labs peuvent être repris pour pratiquer plusieurs fois.</p></div><div className="flex items-center gap-2 text-sm font-semibold text-forest"><Filter className="h-4 w-4 text-gold-dark" /> Filtrer les formations</div></div><div className="mt-6 flex flex-wrap gap-2">{filters.map((filter) => <button key={filter.id} type="button" onClick={() => setActiveFilter(filter.id)} className={`rounded-full border px-4 py-2 text-sm font-semibold transition ${activeFilter === filter.id ? "border-forest bg-forest text-white" : "border-border bg-white text-forest hover:border-gold"}`}>{filter.label}</button>)}</div></section>
    {showProfessional && <section className="container mx-auto grid gap-5 px-6 pb-16 sm:grid-cols-2 lg:grid-cols-4 lg:px-10"><div className="sm:col-span-2 lg:col-span-4"><h2 className="font-serif text-2xl font-bold text-forest">Parcours professionnels</h2><p className="mt-2 text-muted-foreground">Des parcours diplômants avec certification signée par Global Academy, institution agréée par le MINEFOP.</p></div>{academyPrograms.map((program, i) => <article key={program.title} className="flex flex-col rounded-xl border border-border bg-white p-6 transition hover:-translate-y-1 hover:border-gold hover:shadow-lg"><p className="text-sm font-bold text-gold-dark">{String(i + 1).padStart(2, "0")}</p><h3 className="mt-5 font-serif text-xl font-bold text-forest">{program.title}</h3><p className="mt-4 text-lg font-bold text-forest">{program.price}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{program.mode}</p><p className="mt-4 rounded-md bg-gold/10 px-3 py-2 text-xs font-bold uppercase leading-5 tracking-wide text-gold-dark">{program.diploma}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Le prompt engineering est intégré à tous nos programmes.</p>{program.title.startsWith("AI Trainer") && <p className="mt-3 rounded-md border border-gold/30 bg-sand px-3 py-3 text-sm leading-6 text-forest">En collaboration avec FreelanceConnect, ce parcours prépare les professionnels à proposer leurs services comme AI trainer freelance, à rejoindre une communauté de praticiens et à développer un module d’anglais essentiel à l’entraînement des modèles d’IA.</p>}<div className="mt-5 border-t border-border pt-4"><p className="text-xs font-bold uppercase tracking-wider text-gold-dark">Débouchés à distance</p><ul className="mt-3 flex flex-col gap-2 text-sm text-muted-foreground">{program.jobs.map((job) => <li key={job} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-gold-dark" />{job}</li>)}</ul></div></article>)}</section>}
    {showFree && <section className="bg-sand px-6 py-16 lg:px-10"><div className="container mx-auto"><div className="max-w-2xl"><p className="eyebrow text-gold-dark">Accès libre</p><h2 className="mt-2 font-serif text-3xl font-bold text-forest">Short courses, labs et certifications gratuites</h2><p className="mt-3 leading-7 text-muted-foreground">Commencez simplement, testez vos acquis et revenez sur les labs autant de fois que nécessaire. Ces modules introduisent l’AI Fluency pour étudiants, professionnels, enseignants et entreprises.</p></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visibleFreeCourses.map((course) => <article key={course.title} className="flex flex-col rounded-xl border border-border bg-white p-6 shadow-sm"><div className="flex flex-wrap gap-2">{course.tags.map((tag) => <span key={tag} className="rounded-full bg-gold/15 px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-gold-dark">{tag === "lab" ? "Lab à reprendre" : tag === "certifiante" ? "Certifiante" : tag === "entreprise" ? "Entreprise" : "Short course"}</span>)}</div><h3 className="mt-5 font-serif text-xl font-bold text-forest">{course.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{course.description}</p><p className="mt-5 border-t border-border pt-4 text-sm font-bold text-forest">{course.price} · Certification Global Academy</p></article>)}</div>{visibleFreeCourses.length === 0 && <p className="mt-8 rounded-lg bg-white p-5 text-muted-foreground">Aucune formation ne correspond à ce filtre.</p>}</div></section>}
  </main><Footer /></div>
}
